import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body data-new-gr-c-s-check-loaded="14.1228.0" data-gr-ext-installed="" >
        {children}
      </body>
    </html>
  );
}
